config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
  resources :posts
  resources :comments, only: [:new, :create, :destroy]
  resources :likes, only: [:new, :create]
  # Defines the root path route ("/")

  resources :users do
    member do
      get 'api_token'
    end
  end
  
  namespace :api do
    namespace :v1 do
      resources :posts do
        resources :comments
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post

    return unless user.present?

    can :manage, Post, user_id: user.id
    can %i[create destroy], Comment

    return unless user.role == 'admin'

    can :manage, :all

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :users, foreign_key: 'user_id', class_name: 'User'
  belongs_to :posts, foreign_key: 'post_id', class_name: 'Post'
  after_save :update_comments_counter

  validates :text, presence: true, length: { minimum: 2, maximum: 250 }

  private

  def update_comments_counter
    posts.update(comments_counter: posts.comments.length)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :users, foreign_key: 'user_id', class_name: 'User'
  belongs_to :posts, foreign_key: 'post_id', class_name: 'Post'
  after_save :update_likes_counter

  private

  def update_likes_counter
    posts.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :users, foreign_key: 'user_id', class_name: 'User'
  after_save :update_posts_counter

  # validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  # validates :text, presence: true, length: { minimum: 3, maximum: 250 }
  # validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    users.update(posts_counter: users.posts.length)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'user_id'
  has_many :comments
  has_many :likes, foreign_key: 'user_id'
  after_create :generate_api_token

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private
  def generate_api_token
    self.api_token = Devise.friendly_token
    self.save
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
#   before_action :authenticate_with_token
  before_action :find_comment
  def index
    @comments = Comment.all
    render json: @comments
  end

  def show
    render json: @comment
  end

  def find_comment
    @comment = Comment.find_by_id(params[:id])
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  # before_action :authenticate_user!
  before_action :authenticate_with_token

  protected
 
  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :photo, :bio, :password, :current_password)
    end
  end

  private
  def authenticate_with_token
    if params[:api_token]
      user = User.find_by_api_token(params[:api_token])
      sign_in(user)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @user = current_user
    @comment.users = @user

    @comment.save if @comment.valid?
    redirect_to user_posts_path(@user)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(like_params)
    @user = current_user
    @like.users = @user

    @like.save if @like.valid?
    redirect_to user_posts_path(@user)
  end

  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.includes(:comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @user = current_user
    @post.users = @user

    if @post.save
      redirect_to user_posts_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def api_token
    @user = User.find(params[:id])
    respond_to do |format|
      format.json { render :json => @user.api_token, :status => :ok}
      format.html {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<p>add your comments ... </p>
<%= form_with model: Comment do |form| %>
  <%= form.hidden_field :post_id, value: post.id %>
  <div>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit "Add comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "users.css" %>
    <%= stylesheet_link_tag "posts.css" %>
    <%= stylesheet_link_tag "login.css" %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class=container>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% if user_signed_in? %> 
        Hey there 
        <strong><%= current_user.name%></strong>. 
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
        <%= link_to "GET YOUR API TOKEN", api_token_user_path(current_user) if current_user.present?%>
      <% else %> 
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> 
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with model: Like do |form| %>
  <%= form.hidden_field :post_id, value: post.id %>
  <div>
    <%= form.submit "Like post" %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Text %><br>
    <%= form.text_area :text %><br>
    <% post.errors.full_messages_for(:text).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Submit Post" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<section>
  <div class='single-user'>
    <div class='user-photo'>
      <img src='<%= @user.photo %>' alt='<%= @user.name %> thumbnail' />
    </div>
    <div class='user-name'>
      <h2><%= @user.name %></h2>
      <p>Number of Posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <h4><%= link_to 'Add new Post', new_post_path %></h4>
  <div class='user-posts'>
    <% @user.posts.each do |post| %>
      <div class='list-posts'>
        <h5><%= link_to post.title, user_post_path(@user, post) %></h5>
        <p><%= post.text %></p>
        <span class='like-comment'>
          Comments: <%= post.comments_counter || 0 %>, 
          Likes: <%= post.likes_counter || 0 %> 
        </span>
        <h5><%= render partial: 'likes/form', locals: {post: post} %></h5>
      </div>
      <ul class='post-comment'>
        <% if post.recent_comments.length == 0 %>
          <p>No comments added!</p>
        <% else %>
          <% post.recent_comments.each do |comment| %>
            <li><%= comment.users.name %>: <%= comment.text %></li>
          <% end %>
        <% end %>
        <h5><%= render partial: 'comments/form', locals: {post: post} %></h5>
      </ul>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :Text %><br>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit "Submit Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<section>
  <div class='list-posts'>
    <h3><%= @post.title %> by <%= @post.users.name %> </h3>
    <p><%= @post.text %></p>
    <span class='like-comment'>
      Comments: <%= @post.comments_counter || 0 %>, 
      Likes: <%= @post.likes_counter || 0 %> 
    </span>
  </div>
  <ul class='post-comment'>      
    <% if @post.comments.length == 0 %>
      <p>No comments added!</p>
    <% else %>
      <% @post.comments.each do |comment| %>
          <li>
          <%= comment.users.name %>: <%= comment.text %> 
          <% if can? :destroy, comment %>
            <%= link_to "delete", comment_path(comment), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            } %>
          <% end %>
          </li>
      <% end %>
    <% end %>
  </ul>
  <ul>
      <li>
       <% if can? :update, @post %>
         <%= link_to "Edit post", edit_post_path(@post) %>
       <% end %>
     </li>
     <li>
       <% if can? :destroy, @post %>
         <%= link_to "Delete post", post_path(@post), data: {
                         turbo_method: :delete,
                         turbo_confirm: "Are you sure you want to delete this post?"
                      } %>
       <% end %>
     </li>
  </ul>
</section>

app/views/users/api_token.html.erb
<h5>Your API Token is <%= @user.api_token%></h5>

app/views/users/index.html.erb
<section>
  <ul class='users-list'>
    <% @users.each do |user| %>
      <li class='one-user'>
        <div class='user-photo'>
          <img src='<%= user.photo %>' alt='<%= user.name %> thumbnail' />
        </div>
        <div class='user-name'>
          <h2><%= link_to user.name, user_path(user.id) %></h2>
          <p>Number of Posts: <%= user.posts_counter %></p>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section>
  <div class='one-user'>
    <div class='user-photo'>
      <img src='<%= @user.photo %>' alt='<%= @user.name %> thumbnail' />
    </div>
    <div class='user-name'>
      <h2><%= @user.name %></h2>
      <p>Number of Posts: <%= @user.posts_counter || 0 %></p>
    </div>
  </div>
  <div class='user-bio'>
    <h4>Bio</h4>
    <h5><%= @user.bio %></h5>
  </div>
  <div class='posts'>
    <% @user.posts.each do |post| %>
      <div class='list-posts'>
        <h5><%= link_to post.title, user_post_path(@user, post) %></h5>
        <p><%= post.text %></p>
        <span class='like-comment'>
          Comments: <%= post.comments_counter || 0 %>, 
          Likes: <%= post.likes_counter || 0 %> 
        </span>
      </div>
    <% end %>
  </div>
  <button class='see-btn'>
    <%= link_to 'see all posts', user_posts_path(@user) %>
  </button>
</section>